openapi: 3.0.2
info:
  title: UE Control API
  version: "1.0"
servers:
- url: https://api.server.test/v1
tags:
- description: Testing endpoints
  name: Testing
- description: APIs for UE management
  name: Management
paths:
  /UE/{iMSI}/disconnect:
    put:
      operationId: u_eimsi_disconnect_put
      parameters:
      - explode: false
        in: path
        name: iMSI
        required: true
        schema:
          description: International Mobile Subscriber Identification
          type: string
        style: simple
      responses:
        "200":
          description: Disconnected
      x-openapi-router-controller: ue_server.controllers.default_controller
  /UE/{iMSI}/handover:
    put:
      operationId: u_eimsi_handover_put
      parameters:
      - explode: false
        in: path
        name: iMSI
        required: true
        schema:
          description: International Mobile Subscriber Identification
          type: string
        style: simple
      responses:
        "200":
          description: Handover received
      x-openapi-router-controller: ue_server.controllers.default_controller
  /UE/{iMSI}/test:
    put:
      operationId: u_eimsi_test_put
      parameters:
      - explode: false
        in: path
        name: iMSI
        required: true
        schema:
          description: International Mobile Subscriber Identification
          type: string
        style: simple
      responses:
        "200":
          description: UE exists
      x-openapi-router-controller: ue_server.controllers.default_controller
  /test:
    get:
      operationId: test_get
      responses:
        "200":
          description: API is reachable
      x-openapi-router-controller: ue_server.controllers.default_controller
components:
  schemas: {}
